In [47]:
# --- 2 Units with Astropy ---

In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [49]:
df = pd.read_csv("solar_system.csv")

In [50]:
df.shape
# Before transposing, the DataFrame has 20 rows and 11 columns

(20, 11)

In [51]:
df = df.set_index("Attribute").T # makes the values in the column "attribute" into row labels, swaps rows and columns
df.index.name = "Planet" # names the row labels "planet"
df.reset_index(inplace = True) # converts the row labels into a column
df.columns.name = None # removes the column's name

In [52]:
df.shape
# After transposing, the DataFrame has 10 rows and 21 columns
# The shape changed because the axes were flipped and the column label had to be changed

(10, 21)

In [53]:
print(df.columns)
# 16 columns have units: Mass (10^24kg), Diameter (km), Density (kg/m^3), Gravity (m/s^2), Escape Velocity (km/s), 
#     Rotation Period (hours), Length of Day (hours), Distance from Sun (10^6 km), Perihelion (10^6 km), 
#     Aphelion (10^6 km), Orbital Period (days), Orbital Velocity (km/s), Orbital Inclination (deg), 
#     Obliquity to Orbit (deg), Mean Temperature (C), Surface Pressure (bars)
# 5 columns don't have units: Planet, Orbital Eccentricity, Number of Moons, Ring System?, Global Magnetic Field?

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [54]:
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [55]:
df.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [56]:
for col in df:
    print(df[col].apply(type))
# (a) The actual actual values are strings
# (b) Python doesn't consider strings numbers and can't apply mathmatical functions to them

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Planet, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mass (10^24kg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Diameter (km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Density (kg/m^3), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Gravity (m/s^2), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Escape Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Rotation Period (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Length of Day (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Distance from Sun (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Perihelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Aphelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Period (days), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Inclination (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Eccentricity, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Obliquity to Orbit (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mean Temperature (C), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Surface Pressure (bars), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Number of Moons, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Ring System?, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Global Magnetic Field?, dtype: object

In [57]:
for col in df.iloc[:, 1:20]:
    df[col] = pd.to_numeric(df[col], errors = "coerce")

In [58]:
df.dtypes
# (a) The three different data types now in the DataFrame are string, float, and integer
# (b) A string is a non-numberical collection of symbols, a float is a number with decimal places, and an integer is a whole number
# (c) The planet column is still object because its string was not numerical

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                   float64
Global Magnetic Field?          object
dtype: object

In [59]:
def attach_units(df, old_col, unit, new_col = None):
    df[old_col] = [val * unit for val in df[old_col]]
    if new_col is not None:
        df.rename(columns={old_col: new_col}, inplace = True)
    return df

In [60]:
my_unit = 1e6 * u.km
my_old_col = "Distance from Sun (10^6 km)"
my_new_col = "Distance from Sun (km)"

attach_units(df, my_old_col, my_unit, my_new_col)

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57900000.0 km,46.000,...,88.0,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes
1,Venus,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108200000.0 km,107.500,...,224.7,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No
2,Earth,5.970,12756,5514,9.8,11.2,23.9,24.0,149600000.0 km,147.100,...,365.2,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,384000.0 km,0.363,...,27.3,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228000000.0 km,206.700,...,687.0,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No
5,Jupiter,1898.000,142984,1326,23.1,59.5,9.9,9.9,778500000.0 km,740.600,...,4331.0,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes
6,Saturn,568.000,120536,687,9.0,35.5,10.7,10.7,1432000000.0 km,1357.600,...,10747.0,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes
7,Uranus,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867000000.0 km,2732.700,...,30589.0,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes
8,Neptune,102.000,49528,1638,11.0,23.5,16.1,16.1,4515000000.0 km,4471.100,...,59800.0,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes
9,Pluto,0.013,2376,1850,0.7,1.3,-153.3,153.3,5906400000.0 km,4436.800,...,90560.0,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown

In [61]:
print(df["Distance from Sun (km)"])

0      57900000.0 km
1     108200000.0 km
2     149600000.0 km
3        384000.0 km
4     228000000.0 km
5     778500000.0 km
6    1432000000.0 km
7    2867000000.0 km
8    4515000000.0 km
9    5906400000.0 km
Name: Distance from Sun (km), dtype: object

In [62]:
# 2.3 Data Analysis

In [63]:
semi_major_axis = []
for i, j in zip(df["Perihelion (10^6 km)"], df["Aphelion (10^6 km)"]):
    semi_major_axis.append((i + j)/2)
semi_major_axis

[57.9, 108.2, 149.6, 0.3845, 228.0, 778.5, 1432.05, 2867.05, 4515.0, 5906.35]

In [64]:
df.insert(11, "Semi Major Axis (10^6 km)", semi_major_axis)

In [65]:
df.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)',
       'Semi Major Axis (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [66]:
df["Semi Major Axis (10^6 km)"]

0      57.9000
1     108.2000
2     149.6000
3       0.3845
4     228.0000
5     778.5000
6    1432.0500
7    2867.0500
8    4515.0000
9    5906.3500
Name: Semi Major Axis (10^6 km), dtype: float64

In [67]:
my_unit = 1e6 * u.km
my_old_col = "Semi Major Axis (10^6 km)"
my_new_col = "Semi Major Axis (km)"

attach_units(df, my_old_col, my_unit, my_new_col)

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57900000.0 km,46.000,...,88.0,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes
1,Venus,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108200000.0 km,107.500,...,224.7,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No
2,Earth,5.970,12756,5514,9.8,11.2,23.9,24.0,149600000.0 km,147.100,...,365.2,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,384000.0 km,0.363,...,27.3,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228000000.0 km,206.700,...,687.0,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No
5,Jupiter,1898.000,142984,1326,23.1,59.5,9.9,9.9,778500000.0 km,740.600,...,4331.0,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes
6,Saturn,568.000,120536,687,9.0,35.5,10.7,10.7,1432000000.0 km,1357.600,...,10747.0,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes
7,Uranus,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867000000.0 km,2732.700,...,30589.0,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes
8,Neptune,102.000,49528,1638,11.0,23.5,16.1,16.1,4515000000.0 km,4471.100,...,59800.0,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes
9,Pluto,0.013,2376,1850,0.7,1.3,-153.3,153.3,5906400000.0 km,4436.800,...,90560.0,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown

In [68]:
df["Semi Major Axis (km)"]

0      57900000.0 km
1     108200000.0 km
2     149600000.0 km
3        384500.0 km
4     228000000.0 km
5     778500000.0 km
6    1432050000.0 km
7    2867050000.0 km
8    4515000000.0 km
9    5906350000.0 km
Name: Semi Major Axis (km), dtype: object

In [69]:
orbital_period = df["Orbital Period (days)"]
my_unit = 1 * u.day
my_old_col = "Orbital Period (days)"

attach_units(df, my_old_col, my_unit)

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57900000.0 km,46.000,...,88.0 d,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes
1,Venus,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108200000.0 km,107.500,...,224.7 d,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No
2,Earth,5.970,12756,5514,9.8,11.2,23.9,24.0,149600000.0 km,147.100,...,365.2 d,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,384000.0 km,0.363,...,27.3 d,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228000000.0 km,206.700,...,687.0 d,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No
5,Jupiter,1898.000,142984,1326,23.1,59.5,9.9,9.9,778500000.0 km,740.600,...,4331.0 d,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes
6,Saturn,568.000,120536,687,9.0,35.5,10.7,10.7,1432000000.0 km,1357.600,...,10747.0 d,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes
7,Uranus,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867000000.0 km,2732.700,...,30589.0 d,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes
8,Neptune,102.000,49528,1638,11.0,23.5,16.1,16.1,4515000000.0 km,4471.100,...,59800.0 d,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes
9,Pluto,0.013,2376,1850,0.7,1.3,-153.3,153.3,5906400000.0 km,4436.800,...,90560.0 d,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown

In [70]:
df["Orbital Period (days)"]

0       88.0 d
1      224.7 d
2      365.2 d
3       27.3 d
4      687.0 d
5     4331.0 d
6    10747.0 d
7    30589.0 d
8    59800.0 d
9    90560.0 d
Name: Orbital Period (days), dtype: object

In [71]:
df["Orbital Period (years)"] = [period.to(u.year) for period in df["Orbital Period (days)"]]

In [72]:
df.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Semi Major Axis (km)',
       'Orbital Period (days)', 'Orbital Velocity (km/s)',
       'Orbital Inclination (deg)', 'Orbital Eccentricity',
       'Obliquity to Orbit (deg)', 'Mean Temperature (C)',
       'Surface Pressure (bars)', 'Number of Moons', 'Ring System?',
       'Global Magnetic Field?', 'Orbital Period (years)'],
      dtype='object')

In [73]:
df["Orbital Period (years)"]

0    0.24093086926762491 yr
1     0.6151950718685831 yr
2     0.9998631074606433 yr
3    0.07474332648870637 yr
4     1.8809034907597535 yr
5      11.85763175906913 yr
6     29.423682409308693 yr
7      83.74811772758385 yr
8     163.72347707049965 yr
9     247.93976728268308 yr
Name: Orbital Period (years), dtype: object

In [74]:
df_indexed = df.set_index("Planet")
saturn_period = df_indexed.loc["Saturn", "Orbital Period (years)"]
print(f" Saturn's orbital period is {saturn_period:.4f}!")

 Saturn's orbital period is 29.4237 yr!

In [75]:
# Astronomical units is a unit of measurement equal to the distance between the earth and the sun

In [76]:
const.au

<<class 'astropy.constants.iau2015.IAU2015'> name='Astronomical Unit' value=149597870700.0 uncertainty=0.0 unit='m' reference='IAU 2012 Resolution B2'>

In [77]:
au_value = const.au
au_value.to(u.km)

In [78]:
my_unit = u.AU
my_old_col = "Diameter (km)"
my_new_col = "Diameter (AU)"

attach_units(df, my_old_col, my_unit, my_new_col)

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (km),Perihelion (10^6 km),...,Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Orbital Period (years)
0,Mercury,0.330,4879.0 AU,5429,3.7,4.3,1407.6,4222.6,57900000.0 km,46.000,...,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes,0.24093086926762491 yr
1,Venus,4.870,12104.0 AU,5243,8.9,10.4,-5832.5,2802.0,108200000.0 km,107.500,...,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No,0.6151950718685831 yr
2,Earth,5.970,12756.0 AU,5514,9.8,11.2,23.9,24.0,149600000.0 km,147.100,...,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes,0.9998631074606433 yr
3,Moon,0.073,3475.0 AU,3340,1.6,2.4,655.7,708.7,384000.0 km,0.363,...,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No,0.07474332648870637 yr
4,Mars,0.642,6792.0 AU,3934,3.7,5.0,24.6,24.7,228000000.0 km,206.700,...,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No,1.8809034907597535 yr
5,Jupiter,1898.000,142984.0 AU,1326,23.1,59.5,9.9,9.9,778500000.0 km,740.600,...,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes,11.85763175906913 yr
6,Saturn,568.000,120536.0 AU,687,9.0,35.5,10.7,10.7,1432000000.0 km,1357.600,...,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes,29.423682409308693 yr
7,Uranus,86.800,51118.0 AU,1270,8.7,21.3,-17.2,17.2,2867000000.0 km,2732.700,...,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes,83.74811772758385 yr
8,Neptune,102.000,49528.0 AU,1638,11.0,23.5,16.1,16.1,4515000000.0 km,4471.100,...,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes,163.72347707049965 yr
9,Pluto,0.013,2376.0 AU,1850,0.7,1.3,-153.3,153.3,5906400000.0 km,4436.800,...,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown,247.93976728268308 yr

In [79]:
my_unit = u.AU
my_old_col = "Distance from Sun (km)"
my_new_col = "Distance from Sun (AU)"

attach_units(df, my_old_col, my_unit, my_new_col)

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (10^6 km),...,Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Orbital Period (years)
0,Mercury,0.330,4879.0 AU,5429,3.7,4.3,1407.6,4222.6,57900000.0 AU km,46.000,...,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes,0.24093086926762491 yr
1,Venus,4.870,12104.0 AU,5243,8.9,10.4,-5832.5,2802.0,108200000.0 AU km,107.500,...,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No,0.6151950718685831 yr
2,Earth,5.970,12756.0 AU,5514,9.8,11.2,23.9,24.0,149600000.0 AU km,147.100,...,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes,0.9998631074606433 yr
3,Moon,0.073,3475.0 AU,3340,1.6,2.4,655.7,708.7,384000.0 AU km,0.363,...,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No,0.07474332648870637 yr
4,Mars,0.642,6792.0 AU,3934,3.7,5.0,24.6,24.7,228000000.0 AU km,206.700,...,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No,1.8809034907597535 yr
5,Jupiter,1898.000,142984.0 AU,1326,23.1,59.5,9.9,9.9,778500000.0 AU km,740.600,...,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes,11.85763175906913 yr
6,Saturn,568.000,120536.0 AU,687,9.0,35.5,10.7,10.7,1432000000.0 AU km,1357.600,...,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes,29.423682409308693 yr
7,Uranus,86.800,51118.0 AU,1270,8.7,21.3,-17.2,17.2,2867000000.0 AU km,2732.700,...,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes,83.74811772758385 yr
8,Neptune,102.000,49528.0 AU,1638,11.0,23.5,16.1,16.1,4515000000.0 AU km,4471.100,...,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes,163.72347707049965 yr
9,Pluto,0.013,2376.0 AU,1850,0.7,1.3,-153.3,153.3,5906400000.0 AU km,4436.800,...,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown,247.93976728268308 yr

In [80]:
my_unit = 1e6 * u.km
my_old_col = "Perihelion (10^6 km)"
my_new_col = "Perihelion (km)"

attach_units(df, my_old_col, my_unit, my_new_col)

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (km),...,Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Orbital Period (years)
0,Mercury,0.330,4879.0 AU,5429,3.7,4.3,1407.6,4222.6,57900000.0 AU km,46000000.0 km,...,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes,0.24093086926762491 yr
1,Venus,4.870,12104.0 AU,5243,8.9,10.4,-5832.5,2802.0,108200000.0 AU km,107500000.0 km,...,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No,0.6151950718685831 yr
2,Earth,5.970,12756.0 AU,5514,9.8,11.2,23.9,24.0,149600000.0 AU km,147100000.0 km,...,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes,0.9998631074606433 yr
3,Moon,0.073,3475.0 AU,3340,1.6,2.4,655.7,708.7,384000.0 AU km,363000.0 km,...,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No,0.07474332648870637 yr
4,Mars,0.642,6792.0 AU,3934,3.7,5.0,24.6,24.7,228000000.0 AU km,206700000.0 km,...,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No,1.8809034907597535 yr
5,Jupiter,1898.000,142984.0 AU,1326,23.1,59.5,9.9,9.9,778500000.0 AU km,740600000.0 km,...,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes,11.85763175906913 yr
6,Saturn,568.000,120536.0 AU,687,9.0,35.5,10.7,10.7,1432000000.0 AU km,1357600000.0 km,...,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes,29.423682409308693 yr
7,Uranus,86.800,51118.0 AU,1270,8.7,21.3,-17.2,17.2,2867000000.0 AU km,2732700000.0 km,...,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes,83.74811772758385 yr
8,Neptune,102.000,49528.0 AU,1638,11.0,23.5,16.1,16.1,4515000000.0 AU km,4471100000.0 km,...,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes,163.72347707049965 yr
9,Pluto,0.013,2376.0 AU,1850,0.7,1.3,-153.3,153.3,5906400000.0 AU km,4436800000.0 km,...,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown,247.93976728268308 yr

In [81]:
my_unit = u.AU
my_old_col = "Perihelion (km)"
my_new_col = "Perihelion (AU)"

attach_units(df, my_old_col, my_unit, my_new_col)

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (AU),...,Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Orbital Period (years)
0,Mercury,0.330,4879.0 AU,5429,3.7,4.3,1407.6,4222.6,57900000.0 AU km,46000000.0 AU km,...,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes,0.24093086926762491 yr
1,Venus,4.870,12104.0 AU,5243,8.9,10.4,-5832.5,2802.0,108200000.0 AU km,107500000.0 AU km,...,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No,0.6151950718685831 yr
2,Earth,5.970,12756.0 AU,5514,9.8,11.2,23.9,24.0,149600000.0 AU km,147100000.0 AU km,...,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes,0.9998631074606433 yr
3,Moon,0.073,3475.0 AU,3340,1.6,2.4,655.7,708.7,384000.0 AU km,363000.0 AU km,...,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No,0.07474332648870637 yr
4,Mars,0.642,6792.0 AU,3934,3.7,5.0,24.6,24.7,228000000.0 AU km,206700000.0 AU km,...,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No,1.8809034907597535 yr
5,Jupiter,1898.000,142984.0 AU,1326,23.1,59.5,9.9,9.9,778500000.0 AU km,740600000.0 AU km,...,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes,11.85763175906913 yr
6,Saturn,568.000,120536.0 AU,687,9.0,35.5,10.7,10.7,1432000000.0 AU km,1357600000.0 AU km,...,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes,29.423682409308693 yr
7,Uranus,86.800,51118.0 AU,1270,8.7,21.3,-17.2,17.2,2867000000.0 AU km,2732700000.0 AU km,...,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes,83.74811772758385 yr
8,Neptune,102.000,49528.0 AU,1638,11.0,23.5,16.1,16.1,4515000000.0 AU km,4471100000.0 AU km,...,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes,163.72347707049965 yr
9,Pluto,0.013,2376.0 AU,1850,0.7,1.3,-153.3,153.3,5906400000.0 AU km,4436800000.0 AU km,...,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown,247.93976728268308 yr

In [82]:
my_unit = 1e6 * u.km
my_old_col = "Aphelion (10^6 km)"
my_new_col = "Aphelion (km)"

attach_units(df, my_old_col, my_unit, my_new_col)

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (AU),...,Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Orbital Period (years)
0,Mercury,0.330,4879.0 AU,5429,3.7,4.3,1407.6,4222.6,57900000.0 AU km,46000000.0 AU km,...,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes,0.24093086926762491 yr
1,Venus,4.870,12104.0 AU,5243,8.9,10.4,-5832.5,2802.0,108200000.0 AU km,107500000.0 AU km,...,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No,0.6151950718685831 yr
2,Earth,5.970,12756.0 AU,5514,9.8,11.2,23.9,24.0,149600000.0 AU km,147100000.0 AU km,...,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes,0.9998631074606433 yr
3,Moon,0.073,3475.0 AU,3340,1.6,2.4,655.7,708.7,384000.0 AU km,363000.0 AU km,...,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No,0.07474332648870637 yr
4,Mars,0.642,6792.0 AU,3934,3.7,5.0,24.6,24.7,228000000.0 AU km,206700000.0 AU km,...,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No,1.8809034907597535 yr
5,Jupiter,1898.000,142984.0 AU,1326,23.1,59.5,9.9,9.9,778500000.0 AU km,740600000.0 AU km,...,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes,11.85763175906913 yr
6,Saturn,568.000,120536.0 AU,687,9.0,35.5,10.7,10.7,1432000000.0 AU km,1357600000.0 AU km,...,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes,29.423682409308693 yr
7,Uranus,86.800,51118.0 AU,1270,8.7,21.3,-17.2,17.2,2867000000.0 AU km,2732700000.0 AU km,...,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes,83.74811772758385 yr
8,Neptune,102.000,49528.0 AU,1638,11.0,23.5,16.1,16.1,4515000000.0 AU km,4471100000.0 AU km,...,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes,163.72347707049965 yr
9,Pluto,0.013,2376.0 AU,1850,0.7,1.3,-153.3,153.3,5906400000.0 AU km,4436800000.0 AU km,...,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown,247.93976728268308 yr

In [83]:
my_unit = u.AU
my_old_col = "Aphelion (km)"
my_new_col = "Aphelion (AU)"

attach_units(df, my_old_col, my_unit, my_new_col)

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (AU),...,Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Orbital Period (years)
0,Mercury,0.330,4879.0 AU,5429,3.7,4.3,1407.6,4222.6,57900000.0 AU km,46000000.0 AU km,...,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes,0.24093086926762491 yr
1,Venus,4.870,12104.0 AU,5243,8.9,10.4,-5832.5,2802.0,108200000.0 AU km,107500000.0 AU km,...,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No,0.6151950718685831 yr
2,Earth,5.970,12756.0 AU,5514,9.8,11.2,23.9,24.0,149600000.0 AU km,147100000.0 AU km,...,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes,0.9998631074606433 yr
3,Moon,0.073,3475.0 AU,3340,1.6,2.4,655.7,708.7,384000.0 AU km,363000.0 AU km,...,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No,0.07474332648870637 yr
4,Mars,0.642,6792.0 AU,3934,3.7,5.0,24.6,24.7,228000000.0 AU km,206700000.0 AU km,...,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No,1.8809034907597535 yr
5,Jupiter,1898.000,142984.0 AU,1326,23.1,59.5,9.9,9.9,778500000.0 AU km,740600000.0 AU km,...,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes,11.85763175906913 yr
6,Saturn,568.000,120536.0 AU,687,9.0,35.5,10.7,10.7,1432000000.0 AU km,1357600000.0 AU km,...,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes,29.423682409308693 yr
7,Uranus,86.800,51118.0 AU,1270,8.7,21.3,-17.2,17.2,2867000000.0 AU km,2732700000.0 AU km,...,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes,83.74811772758385 yr
8,Neptune,102.000,49528.0 AU,1638,11.0,23.5,16.1,16.1,4515000000.0 AU km,4471100000.0 AU km,...,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes,163.72347707049965 yr
9,Pluto,0.013,2376.0 AU,1850,0.7,1.3,-153.3,153.3,5906400000.0 AU km,4436800000.0 AU km,...,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown,247.93976728268308 yr

In [84]:
my_unit = u.AU
my_old_col = "Semi Major Axis (km)"
my_new_col = "Semi Major Axis (AU)"

attach_units(df, my_old_col, my_unit, my_new_col)

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (AU),...,Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Orbital Period (years)
0,Mercury,0.330,4879.0 AU,5429,3.7,4.3,1407.6,4222.6,57900000.0 AU km,46000000.0 AU km,...,47.4,7.0,0.206,0.034,167,0.00000,0,NaN,Yes,0.24093086926762491 yr
1,Venus,4.870,12104.0 AU,5243,8.9,10.4,-5832.5,2802.0,108200000.0 AU km,107500000.0 AU km,...,35.0,3.4,0.007,177.400,464,92.00000,0,NaN,No,0.6151950718685831 yr
2,Earth,5.970,12756.0 AU,5514,9.8,11.2,23.9,24.0,149600000.0 AU km,147100000.0 AU km,...,29.8,0.0,0.017,23.400,15,1.00000,1,NaN,Yes,0.9998631074606433 yr
3,Moon,0.073,3475.0 AU,3340,1.6,2.4,655.7,708.7,384000.0 AU km,363000.0 AU km,...,1.0,5.1,0.055,6.700,-20,0.00000,0,NaN,No,0.07474332648870637 yr
4,Mars,0.642,6792.0 AU,3934,3.7,5.0,24.6,24.7,228000000.0 AU km,206700000.0 AU km,...,24.1,1.8,0.094,25.200,-65,0.01000,2,NaN,No,1.8809034907597535 yr
5,Jupiter,1898.000,142984.0 AU,1326,23.1,59.5,9.9,9.9,778500000.0 AU km,740600000.0 AU km,...,13.1,1.3,0.049,3.100,-110,NaN,95,NaN,Yes,11.85763175906913 yr
6,Saturn,568.000,120536.0 AU,687,9.0,35.5,10.7,10.7,1432000000.0 AU km,1357600000.0 AU km,...,9.7,2.5,0.052,26.700,-140,NaN,274,NaN,Yes,29.423682409308693 yr
7,Uranus,86.800,51118.0 AU,1270,8.7,21.3,-17.2,17.2,2867000000.0 AU km,2732700000.0 AU km,...,6.8,0.8,0.047,97.800,-195,NaN,28,NaN,Yes,83.74811772758385 yr
8,Neptune,102.000,49528.0 AU,1638,11.0,23.5,16.1,16.1,4515000000.0 AU km,4471100000.0 AU km,...,5.4,1.8,0.010,28.300,-200,NaN,16,NaN,Yes,163.72347707049965 yr
9,Pluto,0.013,2376.0 AU,1850,0.7,1.3,-153.3,153.3,5906400000.0 AU km,4436800000.0 AU km,...,4.7,17.2,0.244,119.500,-225,0.00001,5,NaN,Unknown,247.93976728268308 yr

In [85]:
df_indexed = df.set_index("Planet")
for column in df_indexed.columns:
    sample_value = df_indexed.loc["Saturn", column]
    print(f" Saturn's {column} is {sample_value}")

 Saturn's Mass (10^24kg) is 568.0
 Saturn's Diameter (AU) is 120536.0 AU
 Saturn's Density (kg/m^3) is 687
 Saturn's Gravity (m/s^2) is 9.0
 Saturn's Escape Velocity (km/s) is 35.5
 Saturn's Rotation Period (hours) is 10.7
 Saturn's Length of Day (hours) is 10.7
 Saturn's Distance from Sun (AU) is 1432000000.0 AU km
 Saturn's Perihelion (AU) is 1357600000.0 AU km
 Saturn's Aphelion (AU) is 1506500000.0 AU km
 Saturn's Semi Major Axis (AU) is 1432050000.0 AU km
 Saturn's Orbital Period (days) is 10747.0 d
 Saturn's Orbital Velocity (km/s) is 9.7
 Saturn's Orbital Inclination (deg) is 2.5
 Saturn's Orbital Eccentricity is 0.052
 Saturn's Obliquity to Orbit (deg) is 26.7
 Saturn's Mean Temperature (C) is -140
 Saturn's Surface Pressure (bars) is nan
 Saturn's Number of Moons is 274
 Saturn's Ring System? is nan
 Saturn's Global Magnetic Field? is Yes
 Saturn's Orbital Period (years) is 29.423682409308693 yr

In [86]:
df.to_csv("units.csv", index=False)