In [1]:
# --- 2 Pandas DataFrame ---

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("state_data.csv")

In [4]:
print(df.shape)
# 52 rows and 4 columns

(52, 4)

In [5]:
print(df.head())

  state   latitude   longitude        name
0    AK  63.588753 -154.493062      Alaska
1    AL  32.318231  -86.902298     Alabama
2    AR  35.201050  -91.831833    Arkansas
3    AZ  34.048928 -111.093731     Arizona
4    CA  36.778261 -119.417932  California

In [6]:
print(df.tail())

   state   latitude   longitude           name
47    VT  44.558803  -72.577841        Vermont
48    WA  47.751074 -120.740139     Washington
49    WI  43.784440  -88.787868      Wisconsin
50    WV  38.597626  -80.454903  West Virginia
51    WY  43.075968 -107.290284        Wyoming

In [16]:
#   1.  The first column gives the two-letter state abbreviation, the next two columns give the state's 
# latitude and longitude, and the last column gives the full name of the state
#   2.  The first state is Alaska
#   3.  The last state is Wyoming
#   4. There are 52 total entries
#   5.  The list also contains Puerto Rico and the District of Columbia

In [17]:
df["latitude"].median()
# 39.4355155 is the median latitudew

39.4355155

In [18]:
df["longitude"].median()
# -89.093198 is the median longitude

-89.093198

In [10]:
df["distance to median latitude"] = (df["latitude"].median() - df["latitude"]).abs()
df

,state,latitude,longitude,name,distance to median latitude
0,AK,63.588753,-154.493062,Alaska,24.153237
1,AL,32.318231,-86.902298,Alabama,7.117285
2,AR,35.201050,-91.831833,Arkansas,4.234465
3,AZ,34.048928,-111.093731,Arizona,5.386588
4,CA,36.778261,-119.417932,California,2.657255
5,CO,39.550051,-105.782067,Colorado,0.114536
6,CT,41.603221,-73.087749,Connecticut,2.167705
7,DC,38.905985,-77.033418,District of Columbia,0.529530
8,DE,38.910832,-75.527670,Delaware,0.524684
9,FL,27.664827,-81.515754,Florida,11.770689
10,GA,32.157435,-82.907123,Georgia,7.278081
11,HI,19.898682,-155.665857,Hawaii,19.536834
12,IA,41.878003,-93.097702,Iowa,2.442487
13,ID,44.068202,-114.742041,Idaho,4.632686
14,IL,40.633125,-89.398528,Illinois,1.197609
15,IN,40.551217,-85.602364,Indiana,1.115702
16,KS,39.011902,-98.484246,Kansas,0.423614
17,KY,37.839333,-84.270018,Kentucky,1.596182
18,LA,31.244823,-92.145024,Louisiana,8.190693
19,MA,42.407211,-71.382437,Massachusetts,2.971695
20,MD,39.045755,-76.641271,Maryland,0.389761
21,ME,45.253783,-69.445469,Maine,5.818267
22,MI,44.314844,-85.602364,Michigan,4.879328
23,MN,46.729553,-94.685900,Minnesota,7.294038
24,MO,37.964253,-91.831833,Missouri,1.471263
25,MS,32.354668,-89.398528,Mississippi,7.080848
26,MT,46.879682,-110.362566,Montana,7.444167
27,NC,35.759573,-79.019300,North Carolina,3.675942
28,ND,47.551493,-101.002012,North Dakota,8.115977
29,NE,41.492537,-99.901813,Nebraska,2.057021
30,NH,43.193852,-71.572395,New Hampshire,3.758336
31,NJ,40.058324,-74.405661,New Jersey,0.622808
32,NM,34.972730,-105.032363,New Mexico,4.462786
33,NV,38.802610,-116.419389,Nevada,0.632905
34,NY,43.299428,-74.217933,New York,3.863912
35,OH,40.417287,-82.907123,Ohio,0.981772
36,OK,35.007752,-97.092877,Oklahoma,4.427763
37,OR,43.804133,-120.554201,Oregon,4.368617
38,PA,41.203322,-77.194525,Pennsylvania,1.767806
39,PR,18.220833,-66.590149,Puerto Rico,21.214683
40,RI,41.580095,-71.477429,Rhode Island,2.144579
41,SC,33.836081,-81.163725,South Carolina,5.599435
42,SD,43.969515,-99.901813,South Dakota,4.534000
43,TN,35.517491,-86.580447,Tennessee,3.918025
44,TX,31.968599,-99.901813,Texas,7.466916
45,UT,39.320980,-111.093731,Utah,0.114536
46,VA,37.431573,-78.656894,Virginia,2.003943
47,VT,44.558803,-72.577841,Vermont,5.123287
48,WA,47.751074,-120.740139,Washington,8.315559
49,WI,43.784440,-88.787868,Wisconsin,4.348924
50,WV,38.597626,-80.454903,West Virginia,0.837890
51,WY,43.075968,-107.290284,Wyoming,3.640453

In [22]:
df["distance to median longitude"] = (df["longitude"].median() - df["longitude"]).abs()
df

,state,latitude,longitude,name,distance to median latitude,distance to median longitude
0,AK,63.588753,-154.493062,Alaska,24.153237,65.399864
1,AL,32.318231,-86.902298,Alabama,7.117285,2.190900
2,AR,35.201050,-91.831833,Arkansas,4.234465,2.738635
3,AZ,34.048928,-111.093731,Arizona,5.386588,22.000533
4,CA,36.778261,-119.417932,California,2.657255,30.324734
5,CO,39.550051,-105.782067,Colorado,0.114536,16.688869
6,CT,41.603221,-73.087749,Connecticut,2.167705,16.005449
7,DC,38.905985,-77.033418,District of Columbia,0.529530,12.059780
8,DE,38.910832,-75.527670,Delaware,0.524684,13.565528
9,FL,27.664827,-81.515754,Florida,11.770689,7.577444
10,GA,32.157435,-82.907123,Georgia,7.278081,6.186075
11,HI,19.898682,-155.665857,Hawaii,19.536834,66.572659
12,IA,41.878003,-93.097702,Iowa,2.442487,4.004504
13,ID,44.068202,-114.742041,Idaho,4.632686,25.648843
14,IL,40.633125,-89.398528,Illinois,1.197609,0.305330
15,IN,40.551217,-85.602364,Indiana,1.115702,3.490834
16,KS,39.011902,-98.484246,Kansas,0.423614,9.391048
17,KY,37.839333,-84.270018,Kentucky,1.596182,4.823180
18,LA,31.244823,-92.145024,Louisiana,8.190693,3.051826
19,MA,42.407211,-71.382437,Massachusetts,2.971695,17.710761
20,MD,39.045755,-76.641271,Maryland,0.389761,12.451927
21,ME,45.253783,-69.445469,Maine,5.818267,19.647729
22,MI,44.314844,-85.602364,Michigan,4.879328,3.490834
23,MN,46.729553,-94.685900,Minnesota,7.294038,5.592702
24,MO,37.964253,-91.831833,Missouri,1.471263,2.738635
25,MS,32.354668,-89.398528,Mississippi,7.080848,0.305330
26,MT,46.879682,-110.362566,Montana,7.444167,21.269368
27,NC,35.759573,-79.019300,North Carolina,3.675942,10.073898
28,ND,47.551493,-101.002012,North Dakota,8.115977,11.908814
29,NE,41.492537,-99.901813,Nebraska,2.057021,10.808615
30,NH,43.193852,-71.572395,New Hampshire,3.758336,17.520803
31,NJ,40.058324,-74.405661,New Jersey,0.622808,14.687537
32,NM,34.972730,-105.032363,New Mexico,4.462786,15.939165
33,NV,38.802610,-116.419389,Nevada,0.632905,27.326191
34,NY,43.299428,-74.217933,New York,3.863912,14.875265
35,OH,40.417287,-82.907123,Ohio,0.981772,6.186075
36,OK,35.007752,-97.092877,Oklahoma,4.427763,7.999679
37,OR,43.804133,-120.554201,Oregon,4.368617,31.461003
38,PA,41.203322,-77.194525,Pennsylvania,1.767806,11.898673
39,PR,18.220833,-66.590149,Puerto Rico,21.214683,22.503049
40,RI,41.580095,-71.477429,Rhode Island,2.144579,17.615769
41,SC,33.836081,-81.163725,South Carolina,5.599435,7.929473
42,SD,43.969515,-99.901813,South Dakota,4.534000,10.808615
43,TN,35.517491,-86.580447,Tennessee,3.918025,2.512751
44,TX,31.968599,-99.901813,Texas,7.466916,10.808615
45,UT,39.320980,-111.093731,Utah,0.114536,22.000533
46,VA,37.431573,-78.656894,Virginia,2.003943,10.436304
47,VT,44.558803,-72.577841,Vermont,5.123287,16.515357
48,WA,47.751074,-120.740139,Washington,8.315559,31.646941
49,WI,43.784440,-88.787868,Wisconsin,4.348924,0.305330
50,WV,38.597626,-80.454903,West Virginia,0.837890,8.638295
51,WY,43.075968,-107.290284,Wyoming,3.640453,18.197086

In [12]:
print(df.shape)
# 52 rows and 6 columns

(52, 6)

In [59]:
smallest_latitude_difference = 100
for state in df["distance to median latitude"]:
    if state < smallest_latitude_difference:
        smallest_latitude_difference = state
print(f"\033[1mThe state closest to the median latitude is Utah by {smallest_latitude_difference:.2f}\033[0m")

The state closest to the median latitude is Utah by 0.11

In [60]:
greatest_latitude_difference = 0
for state in df["distance to median latitude"]:
    if state > greatest_latitude_difference:
        greatest_latitude_difference = state
print(f"\033[1mThe state farthest from the median latitude is Alaska by {greatest_latitude_difference:.2f}\033[0m")

The state farthest from the median latitude is Alaska by 24.15

In [63]:
smallest_longitude_difference = 100
for state in df["distance to median longitude"]:
    if state < smallest_longitude_difference:
        smallest_longitude_difference = state
print(f"\033[1mThe state closest from the median latitude is Mississippi by {smallest_longitude_difference:.2f}\033[0m")

The state closest from the median latitude is Mississippi by 0.31

In [65]:
greatest_longitude_difference = 0
for state in df["distance to median longitude"]:
    if state > greatest_longitude_difference:
        greatest_longitude_difference = state
greatest_longitude_difference
print(f"\033[1mThe state farthest from the median longitude is Hawaii by {greatest_longitude_difference:.2f}\033[0m")

The state farthest from the median longitude is Hawaii by 66.57

In [73]:
print(df.memory_usage([]))
# I found this function on the data frame page of the pandas documentation website
# The function shows how much memory every column in the data frame is using in bytes
# This would be helpful to use if you were low on memory and wanted to check which part of your data frame was taking up the most space

state                           416
latitude                        416
longitude                       416
name                            416
distance to median latitude     416
distance to median longitude    416
dtype: int64

In [74]:
# --- 3 Seaborn ---

In [76]:
import matplotlib.pyplot as plt
import seaborn as sns